language: python
python:
  - "2.7"
node_js:
- '8'

services:
  - docker

install:
  - pip install -r requirements.txt
  - npm install
  - npm install -g mocha
# command to run tests
script:
  - python test.py
  - mocha test.js --reporter dot

after_success:
  - echo "JWT_SECRET=$PROD_JWT_SECRET" > .env
  - echo "PORT=80" > .env
  - docker build -t nickpearson/comicgame .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nickpearson/comicgame:latest
