language: python
python:
  - "2.7"
  - "3.3"
  - "3.6"
node_js:
- '8'


install:
  - pip install -r requirements.txt
  - npm install
  - npm install -g mocha
# command to run tests
script:
  - python test.py
  - mocha test.js --reporter dot
