apiVersion: v1
kind: Namespace
metadata:
  name: comicgame-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comicgame
  namespace: comicgame-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comicgame-app
  template:
    metadata:
      labels:
        app: comicgame-app
    spec:
      containers:
      - name: comicgame
        image: nickpearson/comicgame:latest
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        ports:
        - name: web
          containerPort: 80
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: jwt_secret
        - name: OCI_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: oci_user
        - name: OCI_TENNANT
          valueFrom:
            secretKeyRef:
              name: secrets
              key: oci_tennant
        - name: OCI_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: oci_secret
        - name: MONGO_HOST
          value: database-ss-0.database-svc
        - name: MONGO_RS
          value: rs0
---
apiVersion: v1
kind: Service
metadata:
 name: comicgame-svc
 namespace: comicgame-ns
spec:
 type: LoadBalancer
 selector:
   app: comicgame-app
 ports:
    - port: 80
      targetPort: web
 selector:
   app: comicgame-app
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: comicgame-autoscaler
  namespace: comicgame-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: comicgame
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
# MONGO DB STUFFS
apiVersion: v1
kind: Service
metadata:
  name: database-svc
  namespace: comicgame-ns
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: db
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: database-ss
  namespace: comicgame-ns
spec:
  serviceName: "database-svc"
  replicas: 1
  template:
    metadata:
      labels:
        role: db
        environment: comicgame
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: database
        image: mongo
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: db-storage
          mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 250m
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=db,environment=comicgame"
          - name: KUBE_NAMESPACE
            value: comicgame-ns
  volumeClaimTemplates:
  - metadata:
      name: db-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "oci"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: database-autoscaler
  namespace: comicgame-ns
spec:
  scaleTargetRef:
   apiVersion: apps/v1
   kind: StatefulSet
   name: database-ss
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
